export const registerFormControls = [
  {
    name: "userName",
    label: "User Name",
    placeholder: "Enter your user name",
    componentType: "input",
    type: "text",
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const loginFormControls = [
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const addProductFormElements = [
  {
    label: "Title",
    name: "title",
    componentType: "input",
    type: "text",
    placeholder: "Enter product title",
  },
  {
    label: "Description",
    name: "description",
    componentType: "textarea",
    placeholder: "Enter product description",
  },
  {
    label: "Category",
    name: "category",
    componentType: "select",
    options: [
      { id: "men", label: "Men" },
      { id: "women", label: "Women" },
      { id: "kids", label: "Kids" },
      { id: "accessories", label: "Accessories" },
      { id: "footwear", label: "Footwear" },
    ],
  },
  {
    label: "Brand",
    name: "brand",
    componentType: "select",
    options: [
      { id: "nike", label: "Nike" },
      { id: "adidas", label: "Adidas" },
      { id: "puma", label: "Puma" },
      { id: "levi", label: "Levi's" },
      { id: "zara", label: "Zara" },
      { id: "h&m", label: "H&M" },
    ],
  },
  {
    label: "Price",
    name: "price",
    componentType: "input",
    type: "number",
    placeholder: "Enter product price",
  },
  {
    label: "Sale Price",
    name: "salePrice",
    componentType: "input",
    type: "number",
    placeholder: "Enter sale price (optional)",
  },
  {
    label: "Total Stock",
    name: "totalStock",
    componentType: "input",
    type: "number",
    placeholder: "Enter total stock",
  },
];

export const shoppingViewHeaderMenuItems = [
  {
    id: "home",
    label: "Home",
    path: "/shop/home",
  },
  {
    id: "products",
    label: "Products",
    path: "/shop/listing",
  },
  {
    id: "search",
    label: "Search",
    path: "/shop/search",
  },
];

export const categoryOptionsMap = {
  men: "Men",
  women: "Women",
  kids: "Kids",
  boys: "Boys",
  girls: "Girls",
  accessories: "Accessories",
  footwear: "Footwear",
};

export const brandOptionsMap = {
  khushalk: "Khushal K",
  inweave: "InWeave",
  anubhutee: "Anubhutee",
  nayo: "Nayo",
  ahika: "AHIKA",
  soch: "Soch",
  libas: "Libas",
  ahalyaa: "Ahalyaa",
  anouk: "Anouk",
  varanga: "Varanga",
  vishudh: "Vishudh",
  shewill: "SheWill",
  charu: "Charu",
  jaipuribunaai: "JAIPURI BUNAAI",
  kalini: "KALINI",
  indoera: "Indo Era",
  toulin: "TOULIN",
  ishin: "Ishin",
  virahfashion: "Virah Fashion",
  kvsfab: "Kvsfab",
  modarapido: "Moda Rapido",
  fashor: "FASHOR",
  indiinside: "Indi INSIDE",
  sangria: "Sangria",
  myshka: "Myshka",
  rustorange: "Rustorange",
  stylum: "Stylum",
  inddus: "Inddus",
  anayna: "anayna",
  biba: "Biba",
  yufta: "Yufta",
  divena: "Divena",
  jaipurkurti: "Jaipur Kurti",
  w: "W",
  globus: "Globus",
  janasya: "Janasya",
  aurelia: "AURELIA",
  max: "Max",
  ketch: "KETCH",
  taavi: "Taavi",
  fabindia: "Fabindia",
  indya: "INDYA",
  sassafras: "SASSAFRAS",
  athena: "Athena",
  roadster: "Roadster",
  mastharbour: "Mast & Harbour",
  pluss: "PlusS",
  "h&m": "H&M",
  tokyotalkies: "Tokyo Talkies",
  urbanic: "URBANIC",
  mango: "MANGO",
  jockey: "Jockey",
  fablestreet: "FableStreet",
  faballey: "FabAlley",
  only: "ONLY",
  levis: "Levis",
  veromoda: "Vero Moda",
  dressberry: "DressBerry",
  nike: "Nike",
  and: "AND",
  bebe: "Bebe",
  invictus: "INVICTUS",
  montecarlo: "Monte Carlo",
  rangriti: "Rangriti",
  americaneagleoutfitters: "AMERICAN EAGLE OUTFITTERS",
  flyingmachine: "Flying Machine",
  globaldesi: "Global Desi",
  forevernew: "Forever New",
  vanheusen: "Van Heusen",
  enamor: "Enamor",
  rareism: "RAREISM",
  labelritukumar: "Label Ritu Kumar",
  stylestone: "StyleStone",
  guess: "GUESS",
  nautica: "Nautica",
  trendyol: "Trendyol",
  freakins: "FREAKINS",
  calvinkleinjeans: "Calvin Klein Jeans",
  woodland: "Woodland",
  people: "People",
  pepejeans: "Pepe Jeans",
  spykar: "SPYKAR",
  showoff: "SHOWOFF",
  gant: "GANT",
  zinklondon: "Zink London",
  unitedcolorsofbenetton: "United Colors of Benetton",
  campussutra: "Campus Sutra",
  elle: "ELLE",
  beinghuman: "Being Human",
  cantabil: "Cantabil",
  coverstory: "COVER STORY",
  aeropostale: "Aeropostale",
  gocolors: "Go Colors",
  zivame: "Zivame",
  kappa: "Kappa",
  puma: "Puma",
  amante: "Amante",
  tommyhilfiger: "Tommy Hilfiger",
  underarmour: "UNDER ARMOUR",
  blissclub: "BlissClub",
  adidas: "ADIDAS",
  bewakoof: "Bewakoof",
  thesouledstore: "The Souled Store",
  hummel: "hummel",
  sweetdreams: "Sweet Dreams",
  cultsport: "Cultsport",
  slazenger: "Slazenger",
  clovia: "Clovia",
  ethnicity: "Ethnicity",
  juniper: "Juniper",
  lakshita: "Lakshita",
  ancestry: "Ancestry",
  kazo: "Kazo",
  imara: "IMARA",
  uspoloassnwomen: "U.S. Polo Assn. Women",
  columbia: "Columbia",
  ksut: "KSUT",
  ritukumar: "Ritu Kumar",
  cottonon: "COTTON ON",
  femella: "Femella",
  eavan: "Eavan",
  latinquarters: "Latin Quarters",
  masaba: "Masaba",
  aks: "AKS",
  shree: "Shree",
  suta: "Suta",
  meenabazaar: "Meena Bazaar",
  pothys: "Pothys",
  gosriki: "GoSriKi",
  taneira: "Taneira",
  newbalance: "New Balance",
  alcis: "Alcis",
  fila: "FILA",
  reebok: "Reebok",
  uspoloassn: "U.S. Polo Assn.",
  splash: "Splash",
  dillinger: "DILLINGER",
  londonrag: "London Rag",
  lee: "Lee",
  jackandjones: "Jack & Jones",
  louisphilippe: "Louis Philippe",
  blackberrys: "Blackberrys",
  wrogn: "WROGN",
  allensolly: "Allen Solly",
  gap: "GAP",
  calvinklein: "Calvin Klein",
  superdry: "SUPERDRY",
  redtape: "RED TAPE",
  lacoste: "Lacoste",
  wrangler: "WRANGLER",
  killer: "Killer",
  celio: "Celio",
  mufti: "MUFTI",
  royalenfield: "Royal Enfield",
  indianterrain: "Indian Terrain",
  sparx: "Sparx",
  crocs: "Crocs",
  skechers: "Skechers",
  campus: "Campus",
  liberty: "Liberty",
  mochi: "Mochi",
  asics: "ASICS",
  bata: "Bata",
  birkenstock: "Birkenstock",
  metro: "Metro",
  hushpuppies: "Hush Puppies",
};

export const filterOptions = {
  category: [
    { id: "men", label: "Men" },
    { id: "women", label: "Women" },
    { id: "kids", label: "Kids" },
    { id: "accessories", label: "Accessories" },
    { id: "footwear", label: "Footwear" },
  ],
  brand: [
    { id: "hrx", label: "HRX" },
    { id: "nike", label: "Nike" },
    { id: "adidas", label: "Adidas" },
    { id: "puma", label: "Puma" },
    { id: "levis", label: "Levi's" },
    { id: "h&m", label: "H&M" },
    { id: "redtape", label: "Redtape" },
    { id: "tommyhilfiger", label: "Tommy Hilfiger" },
    { id: "lacoste", label: "Lacoste" },
    { id: "allensolly", label: "Allen Solly" },
    { id: "superdry", label: "Superdry" },
    { id: "underarmour", label: "Under Armour" },
    { id: "roadster", label: "Roadster" },
    { id: "max", label: "Max" },
    { id: "soch", label: "Soch" },
    { id: "libas", label: "Libas" },
    { id: "anouk", label: "Anouk" },
    { id: "sangria", label: "Sangria" },
    { id: "biba", label: "Biba" },
    { id: "aurelia", label: "Aurelia" },
    { id: "fabindia", label: "Fabindia" },
    { id: "gap", label: "GAP" },
    { id: "skechers", label: "Skechers" },
    { id: "vanhuesen", label: "Van Heusen" },
    { id: "only", label: "ONLY" },
    { id: "giniandjony", label: "Gini and Jony" },
    { id: "flyingmachine", label: "Flying Machine" },
  ],
};

export const sortOptions = [
  { id: "price-lowtohigh", label: "Price: Low to High" },
  { id: "price-hightolow", label: "Price: High to Low" },
  { id: "title-atoz", label: "Title: A to Z" },
  { id: "title-ztoa", label: "Title: Z to A" },
];

export const addressFormControls = [
  {
    label: "Address",
    name: "address",
    componentType: "input",
    type: "text",
    placeholder: "Enter your address",
  },
  {
    label: "City",
    name: "city",
    componentType: "input",
    type: "text",
    placeholder: "Enter your city",
  },
  {
    label: "Pincode",
    name: "pincode",
    componentType: "input",
    type: "text",
    placeholder: "Enter your pincode",
  },
  {
    label: "Phone",
    name: "phone",
    componentType: "input",
    type: "text",
    placeholder: "Enter your phone number",
  },
  {
    label: "Notes",
    name: "notes",
    componentType: "textarea",
    placeholder: "Enter any additional notes",
  },
];
